version: "3.9"

services:

  # Database
  playground_database:
    image: postgres
    container_name: playground_database
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
